name: GabriTotems
version: 1.2
main: me.gabristudio.GabriTotems
api-version: 1.16
author: GabriDev
description: t.me/GabriStudio :0
softdepend: [PlaceholderAPI]
website: https://github.com/GabriDev-Studio/GabriTotems

commands:
  gabritotems:
    description: Управление тотемами
    usage: /gabritotems <reload|give|list>
    aliases: [gtotems]
    permission: gabritotems.admin
  totem:
    description: Управление тотемами
    usage: /gabritotems <reload|give|list>
    aliases: [gtotems]
    permission: gabritotems.admin

permissions:
  gabritotems.admin:
    description: Полный доступ к командам
    default: op
  gabritotems.use.*:
    description: Использование всех тотемов
    default: true